### PR TITLE
Update the example notebooks

### PR DESCRIPTION
**Pull request by Sheshuk**
Updated the example notebooks to:
* Use the models registry initialization
* Use the `get_flux` function instead of `get_*_spectra`

### CODE REVIEW

**Comment by Sheshuk** [comment]
I've rewritten the example notebooks, to be consistent with https://github.com/SNEWS2/snewpy/pull/296
@JostMigenda could you take a look, if these examples showing all the needed behaviour?

**Comment by JostMigenda** [comment]
Thanks, this looks good! I’ve added a commit demonstrating how `SupernovaModel.param` shows the available progenitors (and included a few bits of minor cleanup, too). If you’re happy with those changes, I think this PR can be merged.

**Comment by Sheshuk** [comment]
Thanks! Is there a reason, why you add notebooks without the output? 
If we keep the plots, the notebooks become something like reference documentation: they can be viewed on GitHub instead of downloading it and trying to get the result.

But of course that makes our diffs much heavier...

**Comment by JostMigenda** [comment]
Mainly for the large overhead in the diffs, yes; but also because storing the outputs in the notebooks means they can become outdated if we make changes to SNEWPY that affect outputs.

I think the cleanest solution for notebooks-as-reference-docs would be to generate the output as part of the docs build. In principle, that should be possible with Sphinx and readthedocs (see SNEWS2/snewpy#185), but it hasn’t been high enough on my to-do list so far.

**Pull request merged**
